"""Add user model fields is_validated

Revision ID: a072302718e1
Revises: d04204b43478
Create Date: 2021-09-13 19:46:59.581327

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision = 'a072302718e1'
down_revision = 'd04204b43478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.drop_constraint('user_pkey', 'user')
    op.alter_column('user', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_primary_key('pk_user', 'user', ['id'])
    op.create_index(op.f('ix_user_is_verified'), 'user', ['is_verified'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_is_verified'), table_name='user')
    op.alter_column('user', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_column('user', 'is_verified')
    # ### end Alembic commands ###
